INSERT INTO `Medication` (`M_ID`,`MedName`,`Dosage`)
VALUES
  ("M1","Gianvi","5"),
  ("M2","Oxycodone/APAP","10"),
  ("M3","Vyvanse","1"),
  ("M4","Lovastatin","2"),
  ("M5","Levothyroxine Sodium","1"),
  ("M6","Methylprednisolone","10"),
  ("M7","Lantus","10"),
  ("M8","Albuterol","5"),
  ("M9","Metoprolol Succinatee","2"),
  ("M10","Naproxen","2"),
  ("M11","Januvia","2"),
  ("M12","Naproxen","2"),
  ("M13","Lovastatin","10"),
  ("M14","Clonazepam","2"),
  ("M15","Allopurinol","1"),
  ("M16","APAP/Codeine","2"),
  ("M17","Advair Diskus","5"),
  ("M18","Celebrex","2"),
  ("M19","Fluticasone Propionate","10"),
  ("M20","Sulfamethoxazole/Trimethoprim","1");
INSERT INTO `Medication` (`M_ID`,`MedName`,`Dosage`)
VALUES
  ("M21","Alprazolam","1"),
  ("M22","Simvastatin","5"),
  ("M23","Methylprednisolone","1"),
  ("M24","Lantus Solostar","5"),
  ("M25","Amlodipine Besylate","10"),
  ("M26","Lantus Solostar","5"),
  ("M27","Metoprolol Tartrate","2"),
  ("M28","Trazodone HCl","5"),
  ("M29","Sulfamethoxazole/Trimethoprim","1"),
  ("M30","Clonazepam","5"),
  ("M31","Clindamycin HCl","5"),
  ("M32","Synthroid","2"),
  ("M33","Simvastatin","10"),
  ("M34","Lipitor","5"),
  ("M35","Omeprazole (Rx)","10"),
  ("M36","Niaspan","1"),
  ("M37","Nasonex","5"),
  ("M38","Benicar","2"),
  ("M39","Albuterol","1"),
  ("M40","Oxycontin","10");
INSERT INTO `Medication` (`M_ID`,`MedName`,`Dosage`)
VALUES
  ("M41","Atenolol","2"),
  ("M42","Oxycontin","1"),
  ("M43","Niaspan","2"),
  ("M44","Enalapril Maleate","10"),
  ("M45","Risperidone","2"),
  ("M46","Ciprofloxacin HCl","5"),
  ("M47","Tramadol HCl","1"),
  ("M48","Lovaza","1"),
  ("M49","Albuterol","1"),
  ("M50","Lisinopril","1");
