INSERT INTO `ResearchPublication_Authors` (`Rpub_Id`,`Authors`)
VALUES("RPJ-10-PUB", 'Shelby V. Alexander'),
("RPJ-10-PUB", 'Patricia B. Wolfe'),
("RPJ-10-PUB", 'Aaron N. Moody');
INSERT INTO `ResearchPublication_Authors` (`Rpub_Id`,`Authors`)
VALUES("RPJ-16-PUB", 'Amity P. Stark'),
("RPJ-16-PUB", 'Belle I. Zamora'),
("RPJ-16-PUB", 'Shannon P. Levine'),
("RPJ-16-PUB", 'Harrison M. Carey');