use VitalSign_HealthManager;

#Query 1: Give the Patient Details who are adults 
SELECT P_id, P_Name, P_Email, P_Gender
FROM Patients 
WHERE P_Age >=18;

#Query 2: Return the details of the Completed Research Projects  
SELECT Rp_Id, ProjectName, 
P_Description, 
(DATEDIFF(P_EndDate, P_StartDate)) AS Duration
FROM ResearchProject
WHERE Project_Status = 'Completed';

#Query 3: Find the average length of treatment plans for patients for each gender 
SELECT p.P_Gender as Gender, ROUND(avg(DATEDIFF(t.End_Date, t.Start_Date))) AS AvgLengthInDays
FROM TreatmentPlan t
INNER JOIN TreatmentPlan_Patient tp ON t.Tp_Id = tp.Tp_Id
INNER JOIN Patients p ON tp.P_Id = p.P_Id
GROUP BY p.P_Gender;

#Query 4: Retrieve the average age of male and female patients who visited the hospital more than twice 
SELECT p.P_Gender as Gender, round(avg(p.P_Age)) as AverageAge
FROM Patients p
INNER JOIN Patient_Visits pv ON p.P_Id = pv.P_Id
GROUP BY p.P_Gender
HAVING count(pv.AppointmentID) >= 2;

#Query 5: Revenue generated by the Hospital from Each Treatment plan and Medication 
SELECT TreatmentPlanID, MedicationName, Revenue
FROM (
    SELECT tp.Tp_Id AS TreatmentPlanID, 
           m.MedName AS MedicationName, 
           SUM(CAST(REPLACE(REPLACE(tp.Rate,"$",""),",","") AS UNSIGNED INTEGER)) as Revenue
    FROM TreatmentPlan tp
    INNER JOIN Medication m ON tp.M_ID = m.M_ID
    GROUP BY tp.Tp_Id, m.MedName
) AS Subquery
ORDER BY Revenue DESC;

#Query 6: Find the Patient and assigned Doctor details where the appointment is “Cancelled”. 
SELECT DISTINCT p.P_Id, p.P_Name, p.P_Email, p.P_Age, p.P_Gender, 
                d.D_Id, d.D_Name, d.D_Age, d.D_Email
FROM Patients p 
INNER JOIN Patient_Visits pv on p.P_Id = pv.P_Id
INNER JOIN Doctor d on d.D_Id = pv.D_Id
WHERE EXISTS (
    SELECT *
    FROM Appointment a
    WHERE a.A_Id = pv.AppointmentID
    AND a.A_Status = 'Cancelled'
);

#Query 7: Top 5 Medications prescribed by doctors, grouped by their dosages 
SELECT  
m.MedName AS MedicationName,  
CONCAT(m.Dosage, " mg") AS Dosage,
COUNT(tp.Tp_Id) AS PrescriptionCount 
FROM Treatmentplan tp 
INNER JOIN Medication m ON tp.M_ID = m.M_ID 
GROUP BY m.MedName, m.Dosage 
HAVING COUNT(tp.Tp_Id) >= ALL (SELECT COUNT(tp2.Tp_Id) 
                             FROM Treatmentplan tp2 
                             GROUP BY tp2.M_ID) 
ORDER BY 
    COUNT(tp.Tp_Id) DESC;


#Query 8: Select the Ward Details where the ward has a capacity greater than 40 or 
#the ward is associated with the Emergency Department 
SELECT W_Id, W_Supervisor
FROM Ward
WHERE W_Capacity > 40
UNION
SELECT W_Id, W_Supervisor
FROM Ward
WHERE Dept_Id = 'VSHM-14';

#Query 9: To get the Doctor names who has the maximum and minimum number of medical records in the hospital 
WITH Doctor_Count AS (
	SELECT COUNT(*) as DoctorCount, mr.D_Id, d.D_Name
	FROM MedicalRecord mr
    INNER JOIN Doctor d on mr.D_Id = d.D_Id
	GROUP BY mr.D_Id, d.D_Name
)

SELECT 
D_Name, 
DoctorCount
FROM
Doctor_Count
HAVING DoctorCount IN 
	(SELECT Max(DoctorCount)
	 FROM Doctor_Count
	 UNION
	 SELECT Min(DoctorCount)
	 FROM Doctor_Count)
ORDER BY DoctorCount DESC;


#Query 10: Get the count of Cancelled and Completed Appointments, each in a seperate column
SELECT DISTINCT
(SELECT count(*) FROM Appointment WHERE A_Status = 'Completed') AS CompletedCount,
(SELECT count(*) FROM Appointment WHERE A_Status = 'Cancelled') AS CancelledCount 
from Appointment;
